# Generated by Django 2.2.9 on 2023-02-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230216_1343'),
        ('posts', '0004_auto_20230218_2155'),
    ]

    operations = [
    ]
